### ISSUE TITLE
Appium source at http://localhost:4723/wd/hub/session/1c8f1c1e-d547-42e3-a7b7-9354d58c346d/source cannot be received after 10 seconds timeout.

### ISSUE THREAD

**Issue by stephenws** [mykola-mokhnach/Appium-iOS-Inspector#21] opened 2017-05-11 15:00 UTC
@mykola-mokhnach  please help me 
## The problem

I am trying to inspect element using Appium- inspector but as soon as when i hit inspector.html in browser i got error in appium log 
@#[line:0,col:undefined]
[xmldom error]	element parse error: TypeError: source.indexOf is not a function 

and inspector.html url shows Error " Appium source at http://localhost:4723/wd/hub/session/1c8f1c1e-d547-42e3-a7b7-9354d58c346d/source cannot be received after 10 seconds timeout. Click this message to retry."

and could not capture screen to inspect element

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.12.4
* Node.js version (unless using Appium.app|exe):v6.10.1
* Mobile platform/version under test: iOS 10.0.1
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

1 I have added breakpoint in my Automation script
2. Now Start my automation script , script starts exceuting and it stops on Login screen as per my breakpoint added
3 now i hit file:///Users/Mukesh/Downloads/Appium-iOS-Inspector-master/iOS%20Inspector.html Url to inspect element from screen
4 But after hitting URL i below message in my appium terminal and it goes continues.
@#[line:0,col:undefined]
[xmldom error]	element parse error: TypeError: source.indexOf is not a function 
5. And in Url i got message" Appium source at http://localhost:4723/wd/hub/session/1c8f1c1e-d547-42e3-a7b7-9354d58c346d/source cannot be received after 10 seconds timeout. Click this message to retry."
but could not  capture screen .
[Logs.zip](https://github.com/appium/appium/files/993401/Logs.zip)

**Comment by mykola-mokhnach** [comment] 2017-05-11 15:01
Closed as duplicate of https://github.com/appium/appium/issues/8434

**Closed as completed by mykola-mokhnach** 2017-05-11 15:01 UTC
