### ISSUE TITLE
Not able to select the Element

### ISSUE THREAD

**Issue by pavanbachu0604** [mykola-mokhnach/Appium-iOS-Inspector#18] opened 2017-02-03 21:22 UTC
I am not able to select the Element which is being displayed on the screen.
iOS 10.2.1 and Appium 1.6.3
PFA Screen shot
<img width="1355" alt="screen shot 2017-02-03 at 4 21 43 pm" src="https://cloud.githubusercontent.com/assets/21222084/22608921/e7e7569e-ea2c-11e6-86ee-aaac1120447c.png">

**Comment by mykola-mokhnach** [comment] 2017-02-03 21:23
Possible duplicate of https://github.com/mykola-mokhnach/Appium-iOS-Inspector/issues/17

**Comment by cpt-buzz** [comment] 2017-02-18 19:32
Same problem. I get no element tree displayed. Often i get an parse error. 
I have downloaded the new version! Something went wrong!

**Comment by mykola-mokhnach** [comment] 2017-02-18 19:38
@cpt-buzz can you provide the text of the error you get?

**Comment by cpt-buzz** [comment] 2017-02-18 19:42
Well, i get only this screen 
<img width="1439" alt="bildschirmfoto 2017-02-18 um 20 39 15" src="https://cloud.githubusercontent.com/assets/25870027/23096341/b7c5a994-f61a-11e6-9781-17f5532826a0.png">

**Comment by mykola-mokhnach** [comment] 2017-02-18 19:48
I'd like to see javascript console output

**Comment by cpt-buzz** [comment] 2017-02-19 12:31
Do you mean this ? 

[Info] INFO :initSessionId:18 initSessionId... (Logger.js, line 36)
[Info] INFO :undefined:30 success (Logger.js, line 36)
[Info] INFO :undefined:30 [object Object] (Logger.js, line 36)
[Info] INFO :undefined:30 Session Id: c3784e2d-71ec-492e-b087-1387602cd41a (Logger.js, line 36)
[Info] INFO :initAutXml:18 initAutXml... (Logger.js, line 36)
[Info] INFO :undefined:30 error (Logger.js, line 36)
[Info] INFO :initScreenshot:18 initScreenshot... (Logger.js, line 36)
[Log] before calling resize() (iOS Inspector.html, line 24)
[Info] INFO :undefined:30 error (Logger.js, line 36)
[Log] NaN,NaN (inspector.js, line 663)
[Log] couldn t find element at NaN , NaN (inspector.js, line 670)
[Log] NaN,NaN (inspector.js, line 663)
[Log] couldn t find element at NaN , NaN (inspector.js, line 670)
[Log] NaN,NaN (inspector.js, line 663)
[Log] couldn t find element at NaN , NaN (inspector.js, line 670)
[Log] NaN,NaN (inspector.js, line 663)
[Log] couldn t find element at NaN , NaN (inspector.js, line 670)
[Log] NaN,NaN (inspector.js, line 663)
[Log] couldn t find element at NaN , NaN (inspector.js, line 670)
[Log] NaN,NaN (inspector.js, line 663)
[Log] couldn t find element at NaN , NaN (inspector.js, line 670)
[Log] NaN,NaN (inspector.js, line 663)
[Log] couldn t find element at NaN , NaN (inspector.js, line 670)
[Log] NaN,NaN (inspector.js, line 663)
[Log] couldn t find element at NaN , NaN (inspector.js, line 670)
[Log] NaN,NaN (inspector.js, line 663)
[Log] couldn t find element at NaN , NaN (inspector.js, line 670)
[Log] NaN,NaN (inspector.js, line 663)
[Log] couldn t find element at NaN , NaN (inspector.js, line 670)
[Log] NaN,NaN (inspector.js, line 663)
[Log] couldn t find element at NaN , NaN (inspector.js, line 670)
[Log] resized to 428.26086950302124 (inspector1.js, line 39)

**Comment by mykola-mokhnach** [comment] 2017-02-19 13:11
@cpt-buzz something seems to be wrong with your Appium session. What do you see if you open http://localhost:4723/wd/hub/sessions page in browser at the same time?

**Comment by cpt-buzz** [comment] 2017-02-19 16:23
<img width="1307" alt="bildschirmfoto 2017-02-19 um 17 22 53" src="https://cloud.githubusercontent.com/assets/25870027/23104119/2af63642-f6c8-11e6-9e94-c102975f7cac.png">

**Comment by mykola-mokhnach** [comment] 2017-02-19 16:32
This one looks good. And what 

```
http://localhost:4723/wd/hub/session_id/source
```

shows, where **session_id** is the identifier taken from the **id** property of the json object above?

**Comment by cpt-buzz** [comment] 2017-02-19 16:39
<img width="791" alt="bildschirmfoto 2017-02-19 um 17 39 01" src="https://cloud.githubusercontent.com/assets/25870027/23104252/6287e4e6-f6ca-11e6-85ce-6249ba2b5d06.png">

**Comment by mykola-mokhnach** [comment] 2017-02-19 16:42
sorry, wrong url. Try:

```
http://localhost:4723/wd/hub/session/session_id/source
```

instead

**Comment by cpt-buzz** [comment] 2017-02-19 17:03
<img width="1437" alt="bildschirmfoto 2017-02-19 um 18 02 56" src="https://cloud.githubusercontent.com/assets/25870027/23104409/b4fe2a66-f6cd-11e6-9311-e82a4784ecef.png">

**Comment by mykola-mokhnach** [comment] 2017-02-19 17:32
As you can see there is no source provided by Appium server, which means the issue has nothing to do with the inspector itself. The thing might be related to a known XCTest bug, for which Appium has added some workarounds in 1.6.4-beta release.

**Closed as completed by mykola-mokhnach** 2017-02-19 17:32 UTC

**Comment by cpt-buzz** [comment] 2017-02-19 17:37
Ok, might appium 1.6.4-beta should be able to fix my problem?

**Comment by mykola-mokhnach** [comment] 2017-02-19 17:38
you never know until you try
